<div class="nwt">

    <div class="logo">
        <ul>
            <li><a target="_blank" href="https://nordicwebteam.se/om-oss/kontakt/">https://nordicwebteam.se</a>
            <li>Kammakargatan 29 Stockholm</li>
            <li><em>Telefon:</em>08-518 172 00</li>
            <li><em>E-Post:</em> <a target="_blank" href="https://nordicwebteam.se/om-oss/kontakt/">info@nordicwebteam.se</a></li>
        </ul>
    </div>

</div>
